// Generated by CoffeeScript 1.6.3
var Dashboard, Panel;

Panel = (function() {
  function Panel(name, settings) {
    this.name = name;
    this.settings = settings;
    this.id = "_pnl_" + this.name;
  }

  Panel.prototype.init = function() {};

  Panel.prototype.update = function() {};

  return Panel;

})();

Dashboard = (function() {
  var panelContainer;

  panelContainer = {};

  function Dashboard(name) {
    this.name = name;
  }

  Dashboard.prototype._addNewPanel = function(name, settings) {
    var newPanel;
    newPanel = new Panel(name, settings);
    return panelContainer[name] = {
      "panel": newPanel,
      "settings": settings || null
    };
  };

  Dashboard.prototype.createPanel = function(name, settings) {
    return this._addNewPanel(name, settings);
  };

  Dashboard.prototype.addPanel = function(panel) {
    return panelContainer[panel.name] = panel;
  };

  Dashboard.prototype.getPanel = function(name) {
    return panelContainer[name] || null;
  };

  Dashboard.prototype.get = function(name) {
    var o, panels;
    if (name === "panels") {
      panels = [];
      for (name in panelContainer) {
        o = panelContainer[name];
        panels.push(o);
      }
      return panels;
    }
    return null;
  };

  return Dashboard;

})();
